-- Create table (works on H2, PostgreSQL 10+, MySQL 8+)
CREATE TABLE IF NOT EXISTS task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  priority VARCHAR(255),
  description VARCHAR(1000),
  type VARCHAR(255)
);

-- Dummy data
INSERT INTO task (priority, description, type) VALUES ('High',   'first dummy task',  'Bug');
INSERT INTO task (priority, description, type) VALUES ('Low',    'second dummy task', 'Feature');
INSERT INTO task (priority, description, type) VALUES ('Medium', 'third dummy task',  'Chore');




